pantry = {
    "chicken": 500,
    "lemon": 2,
    "cumin": 24,
    "paprika": 18,
    "chilli powder": 7,
    "yogurt": 300,
    "oil": 450,
    "onion": 5,
    "garlic": 9,
    "ginger": 2,
    "tomato puree": 125,
    "almonds": 75,
    "rice": 500,
    "coriander": 20,
    "lime": 3,
    "pepper": 8,
    "egg": 6,
    "pizza": 2,
    "spam": 1,
}

recipes = {
    "Butter chicken": {
        "chicken": 100,
        "lemon": 3,
        "cumin": 3,
        "paprika": 3,
        "chilli powder": 3,
        "yogurt": 20,
        "oil": 3,
        "onion": 4,
        "garlic": 2,
        "ginger": 2,
        "tomato puree": 40,
        "almonds": 15,
        "rice": 60,
        "coriander": 30,
        "lime": 2,
    },
    "Chicken and chips": {
        "chicken": 100,
        "potatoes": 20,
        "salt": 2,
        "malt vinegar": 3,
    },
    "Pizza": [
        "pizza",
    ],
    "Egg sandwich": {
        "egg": 2,
        "bread": 2,
        "butter": 1,
    },
    "Beans on toast": {
        "beans": 1,
        "bread": 1,
    },
    "Spam a la tin": {
        "spam": 1,
        "tin opener": 1,
        "spoon": 1,
    },
}
